- name: Create folder for extracted files
  file:
    path: /home/ubuntu/backend
    state: directory

- name: Extract 'artifact.tar.gz' into '/home/ubuntu/backend'
  ansible.builtin.unarchive:
    src: ~/project/artifact.tar.gz
    dest: /home/ubuntu/backend

- name: Run server
  become: true
  shell: |
    cd /home/ubuntu/backend
    npm install
    npm run build   
    pm2 stop default
    pm2 start npm --name "backend" -- start
